import { motion } from "motion/react";
import { ArrowRight, Bot, Braces, Check, Code2, Compass, Gauge, Globe2, Layers3, Mail, MessageSquare, Rocket, ShieldCheck, Sparkles, Workflow, Zap } from "lucide-react";
import { Link } from "@tanstack/react-router";
import { useState, type FormEvent } from "react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { PageCta, PageHero, SiteFrame } from "@/components/SiteChrome";

const offerings = [
  { icon: Globe2, title: "Websites", copy: "Distinctive, fast websites built around your brand and the decisions visitors need to make.", bullets: ["Strategy and UX", "Responsive development", "CMS and integrations"] },
  { icon: Layers3, title: "Web Applications", copy: "Purpose-built products that simplify complex workflows for teams and customers.", bullets: ["Product design", "Secure dashboards", "Scalable architecture"] },
  { icon: Bot, title: "AI Agents", copy: "Useful agents grounded in your business knowledge, tools, and customer experience.", bullets: ["Support agents", "Internal copilots", "Retrieval systems"] },
  { icon: MessageSquare, title: "Conversational AI", copy: "Natural chat experiences that qualify, guide, book, support, and hand off intelligently.", bullets: ["Website chat", "Lead qualification", "Human handoff"] },
  { icon: Workflow, title: "Automation", copy: "Reliable workflows that connect your tools and remove repetitive operational work.", bullets: ["Process mapping", "System integration", "Monitoring and alerts"] },
  { icon: Braces, title: "APIs & AI Systems", copy: "The technical foundations that make products, data, and intelligent tools work together.", bullets: ["API design", "Model integrations", "Data pipelines"] },
];

const portfolio = [
  { category: "Website", title: "Beauty & Beyond", copy: "A considered e-commerce experience that brought brand, product discovery, and operations into one elegant system.", result: "Stronger discovery", visual: "case-beauty" },
  { category: "Web App", title: "Operations Control Room", copy: "One source of truth for workflows, performance signals, and daily team decisions.", result: "Hours saved weekly", visual: "case-dashboard" },
  { category: "AI", title: "FangScript Assistant", copy: "A conversational assistant that answers, qualifies, and turns intent into booked conversations.", result: "Always-on response", visual: "case-ai" },
  { category: "Website", title: "Al Noor Jewellers", copy: "A luxury digital storefront designed to make craftsmanship feel tangible on every screen.", result: "Premium brand presence", visual: "case-jewellery" },
  { category: "AI", title: "Support Intelligence", copy: "Customer context, knowledge retrieval, and smart escalation in a single service workflow.", result: "Faster resolutions", visual: "case-support" },
  { category: "Automation", title: "Connected Operations", copy: "A dependable automation layer joining enquiries, delivery, reporting, and follow-up.", result: "Less manual work", visual: "case-flow" },
];

const faqs = [
  ["What does FangScript build?", "We design and develop premium websites, custom web applications, AI agents, conversational experiences, workflow automation, and the APIs that connect them."],
  ["What does a typical project cost?", "Scope determines investment. After a short discovery conversation, we provide a clear proposal with deliverables, timing, and a fixed project range before work begins."],
  ["How long does a project take?", "Focused websites often take four to eight weeks. Larger applications, AI systems, and automation programs are planned in phases and may run for eight to sixteen weeks or longer."],
  ["Can you improve an existing product?", "Yes. We can audit, redesign, rebuild, or extend an existing website or application without forcing a complete restart when the foundation is sound."],
  ["Will we own the finished work?", "Yes. Once the agreed project is complete and paid for, your business owns the custom designs and code created for it, excluding standard third-party tools and licenses."],
  ["Do you provide ongoing support?", "Yes. We offer practical post-launch support, monitoring, improvements, and ongoing product partnerships depending on what your team needs."],
  ["How do you keep AI systems accurate?", "We constrain systems to approved knowledge, add clear fallbacks and human handoff, test real scenarios, and monitor quality rather than treating AI as a magic black box."],
  ["Can you connect the tools we already use?", "Usually. We work with modern APIs, webhooks, databases, CRMs, scheduling tools, and automation platforms to create a connected workflow."],
];

export function ServicesPage() {
  return <SiteFrame><main><PageHero eyebrow="Capabilities" title="Digital systems built for" accent="real momentum." copy="Strategy, design, engineering, AI, and automation—brought together around the result your business actually needs." /><section className="inner-section"><div className="section-boundary"><div className="inner-intro"><span>What we do</span><h2>One partner from idea to operation.</h2><p>We choose the right level of technology for the problem, then make every detail feel considered.</p></div><div className="offering-grid">{offerings.map(({ icon: Icon, title, copy, bullets }, i) => <motion.article key={title} className="offering-card" initial={{ opacity: 0, y: 25 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "-80px" }} transition={{ delay: i * .05 }}><Icon /><span>0{i + 1}</span><h3>{title}</h3><p>{copy}</p><ul>{bullets.map((bullet) => <li key={bullet}><Check />{bullet}</li>)}</ul></motion.article>)}</div></div></section><section className="outcomes-band"><div className="section-boundary outcomes-grid"><div><Gauge /><strong>Fast by design</strong><span>Performance and clarity from the first screen.</span></div><div><ShieldCheck /><strong>Built responsibly</strong><span>Accessible, secure, and maintainable foundations.</span></div><div><Rocket /><strong>Ready to grow</strong><span>Systems that can evolve with your business.</span></div></div></section><PageCta title="Have a challenge worth solving?" /></main></SiteFrame>;
}

export function WorkPage() {
  const [filter, setFilter] = useState("All");
  const filters = ["All", "Website", "Web App", "AI", "Automation"];
  const shown = portfolio.filter((item) => filter === "All" || item.category === filter);
  return <SiteFrame><main><PageHero eyebrow="Selected work" title="Products with purpose." accent="Experiences with presence." copy="A selection of websites, applications, agents, and automated systems designed around measurable business needs." /><section className="inner-section work-page"><div className="section-boundary"><div className="work-toolbar"><p>{String(shown.length).padStart(2, "0")} selected projects</p><div className="filters" aria-label="Filter projects">{filters.map((item) => <button key={item} className={filter === item ? "active" : ""} onClick={() => setFilter(item)}>{item}</button>)}</div></div><motion.div layout className="case-grid">{shown.map((item, i) => <motion.article layout key={item.title} className="case-card" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * .05 }}><div className={`case-visual ${item.visual}`}><div className="case-ui"><i /><i /><i /><span /></div></div><div className="case-copy"><span>{item.category}</span><h2>{item.title}</h2><p>{item.copy}</p><footer><strong>{item.result}</strong><ArrowRight /></footer></div></motion.article>)}</motion.div></div></section><PageCta title="Your project could be next." /></main></SiteFrame>;
}

export function AboutPage() {
  const principles = [{ icon: Compass, title: "Clarity before complexity", copy: "We understand the commercial problem before choosing a tool or writing code." }, { icon: Sparkles, title: "Craft with intent", copy: "Every interaction, visual decision, and workflow must earn its place." }, { icon: Code2, title: "Built to endure", copy: "Strong foundations make products easier to operate, improve, and scale." }];
  return <SiteFrame><main><PageHero eyebrow="The studio" title="Small team." accent="Serious capability." copy="FangScript is a focused digital studio for ambitious businesses that value sharp thinking, excellent execution, and a direct working relationship." /><section className="inner-section about-story"><div className="section-boundary story-grid"><div className="story-number">F/S<span>EST. 2025</span></div><div><span className="overline">Our point of view</span><h2>Technology should make business feel simpler.</h2><p>That idea guides every FangScript engagement. We bring product thinking, design, engineering, and automation into one room—so decisions stay connected and the finished system works as one.</p><p>We stay close to the work, communicate plainly, and care about what happens after launch. The result is not just something polished. It is something useful.</p></div></div></section><section className="inner-section principles-section"><div className="section-boundary"><div className="inner-intro"><span>How we work</span><h2>Principles that shape the outcome.</h2></div><div className="principle-grid">{principles.map(({ icon: Icon, title, copy }) => <article key={title}><Icon /><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section><section className="numbers-band"><div className="section-boundary"><div><strong>6+</strong><span>Projects delivered</span></div><div><strong>100%</strong><span>Direct collaboration</span></div><div><strong>4</strong><span>Disciplines, one team</span></div><div><strong>∞</strong><span>Room to evolve</span></div></div></section><PageCta title="Let's make the complex feel clear." /></main></SiteFrame>;
}

export function FaqPage() {
  return <SiteFrame><main><PageHero eyebrow="Questions, answered" title="Clear from the" accent="very beginning." copy="The practical details behind working with FangScript—from first conversation to launch and beyond." /><section className="inner-section faq-page"><div className="section-boundary faq-layout"><div><span className="overline">Common questions</span><h2>What you may want to know.</h2><p>Still deciding what you need? Tell us the business challenge. We can help define the right project.</p><Link to="/contact" className="primary-link compact">Ask us directly <ArrowRight /></Link></div><Accordion type="single" collapsible className="faq-list">{faqs.map(([question, answer], i) => <AccordionItem key={question} value={`item-${i}`}><AccordionTrigger><span><i>{String(i + 1).padStart(2, "0")}</i>{question}</span></AccordionTrigger><AccordionContent><p>{answer}</p></AccordionContent></AccordionItem>)}</Accordion></div></section><PageCta title="Still have a question?" copy="Send it our way. You'll get a clear answer from the people who would work on your project." /></main></SiteFrame>;
}

export function ContactPage() {
  const [sent, setSent] = useState(false);
  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    const subject = encodeURIComponent(`Project enquiry from ${String(data.get("name"))}`);
    const body = encodeURIComponent(`Name: ${data.get("name")}\nEmail: ${data.get("email")}\nCompany: ${data.get("company")}\nProject: ${data.get("project")}\nBudget: ${data.get("budget")}\n\n${data.get("message")}`);
    setSent(true);
    window.location.href = `mailto:hello@fangscript.com?subject=${subject}&body=${body}`;
  };
  return <SiteFrame><main><PageHero eyebrow="Start a project" title="Let's build something" accent="that matters." copy="Share the challenge, the ambition, or even the rough idea. We'll reply with useful next steps—not a generic sales pitch." /><section className="inner-section contact-page"><div className="section-boundary contact-layout"><aside><span className="overline">Contact</span><h2>Begin with a conversation.</h2><p>Tell us enough to understand where you are and what a successful outcome would look like.</p><a href="mailto:hello@fangscript.com"><Mail />hello@fangscript.com</a><div className="contact-note"><Zap /><p><strong>What happens next?</strong><br />We'll review your note, ask any useful questions, and suggest a focused next step.</p></div></aside><form onSubmit={submit}><div className="field-row"><label>Your name<input name="name" required autoComplete="name" placeholder="Jane Smith" /></label><label>Work email<input name="email" required type="email" autoComplete="email" placeholder="jane@company.com" /></label></div><div className="field-row"><label>Company<input name="company" autoComplete="organization" placeholder="Company name" /></label><label>Project type<select name="project" defaultValue=""><option value="" disabled>Select one</option><option>Website</option><option>Web application</option><option>AI agent</option><option>Automation</option><option>Not sure yet</option></select></label></div><label>Indicative budget<select name="budget" defaultValue=""><option value="" disabled>Select a range</option><option>Under $5,000</option><option>$5,000–$15,000</option><option>$15,000–$30,000</option><option>$30,000+</option><option>Let's discuss</option></select></label><label>Tell us about the project<textarea name="message" required rows={6} placeholder="What are you trying to improve, launch, or automate?" /></label><div className="form-submit"><button className="gold-button" type="submit">Prepare Email <ArrowRight /></button><p>{sent ? "Your email app should now be open with the details ready to send." : "Your details stay in your email app until you choose to send."}</p></div></form></div></section></main></SiteFrame>;
}
